#!/bin/bash

mkdir grafana
wget http://grafanarel.s3.amazonaws.com/grafana-1.9.1.tar.gz -O grafana.tar.gz                   &&\
        tar -xzf grafana.tar.gz -C grafana --strip-components=1 &&\
        rm grafana.tar.gz

#echo "deb https://packagecloud.io/grafana/stable/debian/ wheezy main" | sudo tee -a /etc/apt/sources.list
##curl https://packagecloud.io/gpg.key | sudo apt-key add -
#sudo apt-get update
#sudo apt-get install -y grafana
