#!/bin/bash

sudo apt-get update
sudo apt-get install -y nodejs
sudo apt-get install -y npm
sudo apt-get install -y git
git clone https://github.com/etsy/statsd.git
cd statsd
git checkout v0.7.2
npm install statsd-influxdb-backend

